### PR TITLE
JSON Query Filtering Support Added

### PR DESCRIPTION
**Pull request by AhmedMedDev**
I've integrated functionality to interpret JSON queries for filtering data within the package

### CODE REVIEW

**Comment by num8er** [comment]
@AhmedMedDev please, fix style based on styleci recommendation. And if it's possible write a test. I'm a bit skeptical about that tests will pass, cause it uses sqlite db for test runner, I hope it supports `->`

**Comment by num8er** [comment]
@AhmedMedDev please update master branch on Your side and push again.

**Comment by AhmedMedDev** [comment]
@num8er done

**Comment by abbasudo** [comment]
Hey @AhmedMedDev. Thanks for your contribution. can you add some tests so I can see the implications of this feature?

**Comment by Lakshan-Madushanka** [comment]
@AhmedMedDev  As packages is growing, It is crucial to submit new pull requests with relevant test cases.

I am quite skeptical about using the '->' symbol in query strings. Although '->' works with the 'where' clause, we need to manually change other query constraints. For example, if we need to find a JSON column (array) that contains a value, we have to use 'whereJsonContains', etc.

This would be a useful feature with proper implementation.

**Comment by AhmedMedDev** [comment]
@Lakshan-Madushanka I appreciate your review, could you provide some guidance on how you think these features should be implemented more effectively?

**Pull request closed without merging**
